config/routes.rb
Rails.application.routes.draw do
  root "routes#top"

  get '/routes/search',  to: 'routes#search'

  resources :routes
  resources :users, except: [:index]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/message', to: 'users#message'
  post '/message', to: 'users#message_create'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :routes, dependent: :destroy
  has_many :messages, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 1.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @routes = @user.routes.paginate(page: params[:page], :per_page => 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:success] = "入力されたメールアドレスへ登録完了用リンクを送信しました。"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def message
    @message = Message.new
    @messages = current_user.messages.all
  end

  def message_create
    @message = Message.new(message_params)
    @message.save
    redirect_to request.referrer
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def message_params
      params.permit(:user_id, :content)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2>ユーザ編集</h2>
  
  <div class="text-center">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
      </div>
    
      <div class="form-group mt-2">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email %>
      </div>
  
      <div class="form-group mt-2">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>
      </div>
  
      <div class="form-group mt-2">
      <%= f.label :password_confirmation, "パスワード(確認用)" %>
      <%= f.password_field :password_confirmation %>
      </div>
      
      <div class="form-group mt-3">
      <%= f.submit "保存", class: "btn-secondary" %>
      </div>
      <div class="mt-5 mb-5">
      <%= link_to "保存せずに戻る", :back %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/message.html.erb
<div class="container w-50">
  <% if @messages.present? %>
    <% @messages.each do |message| %>
      <div><%= message.user.name %>：<%= message.content %></div>
      <hr>
    <% end %>
  <% end %>
  <%= form_with url: "/message", local: true do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
      <textarea name="content" class="form-control"></textarea>
    </div>
    <div class="text-center">
    <%= f.submit "送信", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="text-center">
<h2>ユーザ新規登録</h2>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', model: @user %>
  <div class="form-group">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  </div>

  <div class="form-group">
  <%= f.label :email, "Email" %>
  <%= f.email_field :email %>
  </div>

  <div class="form-group">
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password %>
  <p>※8文字以上を入力してください。</p>
  </div>

  <div class="form-group">
  <%= f.label :password_confirmation, "パスワード(確認用)" %>
  <%= f.password_field :password_confirmation %>
  </div>

  <div class="form-group">
  <%= f.submit "作成", class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>ユーザ情報</h2>
  
  <div class="text-center">
    <p><strong>Name:</strong><%= @user.name %></p>
    <p><strong>Email:</strong><%= @user.email %></p>

    <% if current_user.routes.exists? %>
      <strong><投稿したルート一覧></strong>
      <div class="text-center">
        <div class="container w-50">
          <ul class="list-group list-group-flush">
            <% @routes.each do |r| %>
              <li class="list-group-item">
                <%= link_to r.name, r, style: "text-decoration: none;" %>
                <%= r.start %>から
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      
      <div class="pagination justify-content-center">
        <%= will_paginate @routes, previous_label: '&lt', next_label: '&gt' %>
      </div>
    <% end %>
    
    <div class="text-end">
      <%= button_to "ユーザ情報を編集する", edit_user_path, method: :get, class: "btn btn-secondary" %><br>
      <%= button_to "ユーザを削除する", current_user, method: :delete, class: "btn btn-warning", data: { confirm: '削除してもよろしいですか?'} %>
      <%= link_to "メッセージ", message_path %>
    </div>
  </div>
</div>