config/routes.rb
Rails.application.routes.draw do
  root "routes#top"

  get '/routes/search',  to: 'routes#search'

  resources :routes
  resources :users, except: [:index]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/message', to: 'users#message'
  post '/message', to: 'users#message_create'

end

app/views/layouts/_footer.html.erb
<footer class="text-center">
<p>© 2022 Masato Katsura All rights reserved.</p>
<p>お問い合わせ・お仕事依頼はこちらまで：masato@ato-k.me</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">chika route</a>
      
  <ul class="nav justify-content-end">

    <li>
    <%= form_with url: routes_search_path, method: :get, local: true do |f| %>
      <div class="d-flex">
      <%= f.text_field :keyword, value: $keyword, class: "form-control me-2", placeholder: "目的地を検索" %>
      <%= f.submit "🔍", class: "btn btn-outline-secondary" %>
      </div>
    <% end %>
    </li>

    <% if logged_in? %>
    <li class="nav-item">
      <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
    </li>

    <% else %>
    <li class="nav-item">
      <%= link_to "ユーザ登録", new_user_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "ログイン", login_path, class: "nav-link" %>
    </li>
    <% end %>
        
  </ul>
</nav>  
<aside class="text-center mt-3">
  <%= link_to "近道一覧を見てみる", routes_path, class: "btn btn-outline-danger" %>
</aside>
<aside class="text-center mt-3">
  <%= link_to "近道を投稿", new_route_path, class: "btn btn-outline-success" %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>chika route</title>
    <meta name="description" content="近道共有アプリ「chika route」">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%# alert %>
    <%# notice %>
    <% flash.each do |message_type, message| %>
      <div class="container w-50">
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>